baseurl = "/"
languageCode = "en-us"
title = ""
theme = "hugo-xmag"
googleAnalytics = ""
disqusShortname = "owarai"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
hasCJKLanguage = true
enableEmoji = true
paginate = 12

[permalinks]
    post = "/post/:year/:month/:day/:slug/"


[[menu.main]]
    name = "订阅"
    url = "/index.xml"
    weight = 2
[[menu.main]]
    name = "加入我们"
    url = "/joinus/"
    weight = 6
[[menu.main]]
    name = "字幕组简介"
    url = "/fansub/"
    weight = 5    
[[menu.main]]
    name = "转载规则"
    url = "/rules/"
    weight = 3    

    
[[menu.top]]
    name = "首页"
    url = "/"
    weight = 1
[[menu.top]]
    name = "分类"
    url = "/categories/"
    weight = 3
[[menu.top]]
    name = "标签"
    url = "/tags/"
    weight = 4
[[menu.top]]
    name = "作品"
    url = "/post/"
    weight = 5
[[menu.top]]
    name = "文章"
    url = "/blog/"
    weight = 6



[params]
    description = "笑神本部"
    summary_length = 2
    github_edit = "https://github.com/tcgriffith/owaraisite/blob/master/content/"
    footer = "Powered by [Hugo](https://gohugo.io/), [blogdown](https://github.com/rstudio/blogdown) & [netlify](https://www.netlify.com/) &copy; [OWARAICLUB](https://owarai.netlify.com/) 2017"

[params.text]
    back = "&larr; 返回首页"
    edit = "编辑此页 &rarr;"
    truncated = "&hellip;"

[params.banner]
    src = "/img/logo.png"

