baseurl = "/"
languageCode = "en-us"
title = "笑神本部"
theme = "hugo-owaraiclub"
googleAnalytics = "UA-107230532-1"
disqusShortname = "owarai"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
hasCJKLanguage = true
enableEmoji = true
paginate = 20
enableGitInfo = true
disablePathToLower = true

refLinksErrorLevel = "WARNING"
refLinksNotFoundURL = '#'




[[menu.top]]
    name = "本部"
    url = "/"
    weight = 1
[[menu.top]]
    name = "节目"
    url = "/bangumis/"
    weight = 3
[[menu.top]]
    name = "段子"
    url = "/neta/"
    weight = 4
[[menu.top]]
    name = "论坛"
    url = "https://d.owaraiclub.com/"
    weight = 10
[[menu.top]]
    name = "搜索"
    url = "/search/"
    weight = 12


[[menu.side]]
    name = "全部"
    url = "/post/"
    weight = 1
    desc = "haha"
[[menu.side]]
    name = "字幕组"
    url = "/categories/"
    weight = 2
[[menu.side]]
    name = "标签"
    url = "/tags/"
    weight = 5
[[menu.side]]
    name = "笑神百科"
    url = "/wiki/"
    weight = 5
[[menu.side]]
    name = "艺人组合(段子)"
    url = "/combi/"
    weight = 6






[[menu.side]]
    name = "RSS订阅"
    url = "/index.xml"
    weight = 8
[[menu.side]]
    name = "转载规则"
    url = "/rules/"
    weight = 9


[params]

    description = "笑神本部"
    summary_length = 2
    github_edit = "https://github.com/tcgriffith/owaraisite/blob/master/content/"
    footer = "Powered by [Hugo](https://gohugo.io/), [blogdown](https://github.com/rstudio/blogdown) & [netlify](https://www.netlify.com/) &copy; [OWARAICLUB](https://owarai.netlify.com/) 2017-2019"
    comment = true
    mainBangumis = ["伦敦之心", "神舌", "ametalk"]
    otherbangumis2 = ["其他", "cut"]    
    otherbangumis = ["段子", "其他", "cut"]
    othertags=["漫才", "短剧", "神舌","ametalk", "男女纠察队"]
    flarumurl="https://d.owaraiclub.com/api/discussions?filter[q]=tag:whatsnew"
    flarum="https://d.owaraiclub.com/d/"
[params.text]
    back = "&larr; 返回首页"
    edit = "&#9988;  编辑本页"
    truncated = "&hellip;"
    tags = "标签"
    combi = "搞笑艺人组合"
    bangumi="节目"
    about_author = "关于作者"
    author_delimiter= "&#x1F575 "
    sharetitle = "来自笑神本部"

[params.banner]
    src = "/img/logo_lh_main.svg"

[taxonomies]
  tag = "tags"
  category = "categories"
  bangumi = "bangumis"
  combi = "combi"
  
