baseurl = "/"
languageCode = "en-us"
title = "笑神本部"
theme = "hugo-xmag"
googleAnalytics = "UA-107230532-1"
disqusShortname = "owarai"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
hasCJKLanguage = true
enableEmoji = true
paginate = 12
enableGitInfo = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"


[[menu.main]]
    name = "RSS订阅"
    url = "/index.xml"
    weight = 6

[[menu.main]]
    name = "成员简介"
    url = "/fansub/"
    weight = 2
[[menu.main]]
    name = "转载规则"
    url = "/rules/"
    weight = 3




[[menu.top]]
    name = "首页"
    url = "/"
    weight = 1
[[menu.top]]
    name = "分部"
    url = "/subteams/"
    weight = 3
[[menu.top]]
    name = "标签"
    url = "/tags/"
    weight = 4
[[menu.top]]
    name = "番组"
    url = "/bangumis/"
    weight = 5
[[menu.top]]
    name = "索引"
    url = "/archives/"
    weight = 6
[[menu.top]]
    name = "留言"
    url = "/crit/"





[params]
    description = "笑神本部"
    summary_length = 2
    github_edit = "https://github.com/tcgriffith/owaraisite/blob/master/content/"
    footer = "Powered by [Hugo](https://gohugo.io/), [blogdown](https://github.com/rstudio/blogdown) & [netlify](https://www.netlify.com/) &copy; [OWARAICLUB](https://owarai.netlify.com/) 2017"
    comment = true

[params.text]
    back = "&larr; 返回首页"
    edit = "&#9988;  编辑本页"
    truncated = "&hellip;"
    tags = "标签： "
    about_author = "关于作者"
    author_delimiter= "&#x1F575"

[params.banner]
    src = "/img/logo.png"

[taxonomies]
  tag = "tags"
  category = "categories"
  bangumi = "bangumis"

